# base image
FROM node:12

# env CHOKIDAR_USEPOLLING=true

WORKDIR /usr/src/app

# install and cache app dependencies
# COPY package.json /myapp/client/package.json
# RUN npm install --silent
# RUN npm install react-scripts@1.1.1 -g --silent